# Generated by Django 5.0.6 on 2024-08-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_alter_customuser_email_bookuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuser',
            name='dentist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookuser',
            name='services',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bookuser',
            name='date',
            field=models.DateField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='bookuser',
            name='time',
            field=models.TimeField(blank=True, max_length=15),
        ),
    ]
