# Generated by Django 5.0.6 on 2024-08-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_bookuser_dentist_bookuser_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuser',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
